### PR TITLE
Update versions used in cli

### PR DESCRIPTION
**Pull request by Sineaggi**
Updates upstream generator and cli versions.

Also fixes a few docs.

### CODE REVIEW

**Review by robbecker-wf — APPROVED** [review]

**Comment by robbecker-wf** [comment]
@gibahjoe Could you review and release a new version that updates to the latest generator version?

**Comment by quyenvsp** [comment]
This PR should merge as soon as possible since dio 5 fix many problems.

note: for people have problems, while waiting author release new version you can manually patch it.
run `mvn package` in openapi-generator-cli then replace .jar file in 

(windows) ~\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\openapi_generator_cli-4.0.0\lib

**Review by gibahjoe — APPROVED** [review]
Thank you

**Comment by robbecker-wf** [comment]
Thanks. Can you publish a new version to pub too?

**Pull request merged**
