### PR TITLE
feat(cli): bump official generator version to 7.9

### PR DESCRIPTION
**Pull request by DmitrySboychakov**

### CODE REVIEW

**Comment by DmitrySboychakov** [comment]
Yet another update of generator
Please consider cutting a release after ;)

**Comment by gibahjoe** [comment]
Thank you for your contribution. However, I am moving away from including a jar in the library and will instead download the jar from a config specified by the user. [You can find the code here](https://github.com/gibahjoe/openapi-generator-dart/blob/3c47aa306cbb390c36cd6f26c63090383d107771/openapi-generator-cli/bin/main.dart#L72)

If you are not okay with this approach, please do let me know your reservations.

**Comment by DmitrySboychakov** [comment]
@gibahjoe didn't read the code at a time, but agree 100% on that approach. 
however, does it mean for enduser to have maven installed on the system? 
if so, maybe it's better to handle that in the github actions instead?

**Comment by DmitrySboychakov** [comment]
that being said, don't mind closing this PR at all.

**Comment by gibahjoe** [comment]
Sorry Just saw your comment. 

No, the user does not have to have maven. The initial way didn't have to combine the multiple jars into a single jar, they could have been used as separate jars. I guess it was just easier having 1 jar instead of 2.

**Comment by gibahjoe** [comment]
That being said, v6.0.0 has been released.

Closing this in favor of #162

**Pull request closed without merging**
