### PR TITLE
Add reserved words mappings generator parameters

### PR DESCRIPTION
**Pull request by robertcsakany**
The parameter passing is tested, but the underlying https://github.com/dart-ogurets/dart-openapi-maven/issues/15 have not been released yet - so the generator jar will be added to this PR later.

### CODE REVIEW

**Comment by gibahjoe** [comment]
Okay. Thank you. And if I understand correctly, this mapping will only take effect when the Dart2-api generator is used right? If so, you might want to update the dartdoc to say so.

**Comment by robertcsakany** [comment]
Okay. The dartoc means the code block comment in the OpenAPI annotation? Or the markdown documentation?

**Comment by gibahjoe** [comment]
> Okay. The dartoc means the code block comment in the OpenAPI annotation? Or the markdown documentation?

Just the code block comment in the annotation.

**Comment by robertcsakany** [comment]
I'm a little bit confused, because I made some comment. I'm not sure what else I have to do.

`
  /// Add reserver words mappings as reservedWord=replacement format.
  ///
  /// --reserved-words-mappings
  final Map<String, String> reservedWordsMappings;
`

**Comment by gibahjoe** [comment]
What I was saying was that the comment should mention that it only works with dart2-api generator. To avoid confusion by consumers of the library

**Comment by robertcsakany** [comment]
Ah. Okay. I misundersood your comment.

**Comment by robertcsakany** [comment]
Okay, done. I checked the code generators and this feature is supported by DIO generaor too.

**Comment by gibahjoe** [comment]
Great. will merge once the jar is available

**Comment by robertcsakany** [comment]
The Dart2-Api generator 3.9 released which contains the required PR, so its ready.

**Pull request merged**
