### PR TITLE
feat: Added option to disable caching

### LINKED ISSUE #144: Add option to disable caching
### Description of the bug

I have a file locally available and don't want the generator to cache it. I cannot disable this behaviour.

### Steps to reproduce

-

### Expected behavior

-

### Logs

_No response_

### Screenshots

_No response_

### Platform

iOS

### Library version

5.0.2

### Flutter version

3.19.4

### Flutter channel

stable

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ricardoboss**
This would fix #144

### CODE REVIEW

**Review by Nexushunter — COMMENTED** [review]
These changes look good. Can you include tests to ensure previous functionality isn't broken.

**Comment by ricardoboss** [comment]
My spec is a local file. That doesn't need caching.

**Comment by gibahjoe** [comment]
In this case, caching is used to store a copy of the API specification (spec) from the last time the generator was run. By comparing the current API spec with the cached version, the system can detect if any changes have been made. If the spec hasn’t changed, the generator skips the code regeneration step, which avoids unnecessary work.

This approach is especially useful when:

The API spec is large: Regenerating code for a large spec can be time-consuming.
Other code generation tools are in use: For instance, if you run build_runner to generate code for JsonSerializable, the API generator won’t unnecessarily regenerate the SDK, as it can see that the spec remains unchanged.

Maybe i will give it another name as `caching` doesnt quite describe its function.

**Comment by ricardoboss** [comment]
That all sounds great in theory. For my use case however, it's not great.

My spec file changes frequently as I am developing the API. Sometimes the system doesn't detect it has changed. (at least as far as I can remember, I've been using my fork for a few months by now)

Look, adding this change has no impact for people who don't want it but gives people who want it a way to get it. It's also not hard to support this. Why the push back?

**Comment by gibahjoe** [comment]
You are right. just wanted to know the use case so I can find an appropriate name for the flag. Thanks for your contribution.

**Comment by gibahjoe** [comment]
Please resolve merge conflicts so this can go out in next release.

**Pull request merged**
